package com.example.schooloperationsystem.rest.dto.response;

public enum ErrorType {
    MISSING_FIRST_NAME,
    MISSING_LAST_NAME,
    MISSING_DATE_OF_BIRTH,
    MISSING_PUPIL_ID,
    MISSING_SCHOOL_CLASS_ID,
    MISSING_GRADE,
    MISSING_CLASS_LETTER,
    MISSING_STAFF_ID,
    MISSING_TEACHER_ID,
    PUPIL_NOT_FOUND,
    TEACHER_NOT_FOUND,
    CLASS_NOT_FOUND,
    STAFF_NOT_FOUND
}
